name: Simple Stats
on:
  # 每天运行一次，或者手动触发
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # === 核心配置 ===
          user: bafuka
          template: classic
          # 只启用 header (头部信息)，它包含头像、Stars、Followers
          base: header
          # 隐藏多余的仓库列表等
          base_indepth: yes 
          config_timezone: Asia/Shanghai
          
          # === 样式微调 ===
          # 调整为透明背景或深色背景
          config_display: regular
          theme: night 
