name: Metrics
on:
  # 每天 0 点更新一次
  schedule: [{cron: "0 0 * * *"}]
  # 允许手动触发
  workflow_dispatch:
  # 每次 push 到 master/main 分支时也会触发
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # 必须配置 token
          token: ${{ secrets.METRICS_TOKEN }}

          # === 核心配置 ===
          user: bafuka
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          
          # === 风格配置 (二次元深色风) ===
          config_display: large
          config_padding: 0, 10 + 5%
          theme: night # 类似 tokyonight 的深色主题
          
          # === 额外插件：语言分析 ===
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          
          # === 额外插件：Star 数和成就 ===
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
